ecommerce-shopping-back/config/routes.rb
Rails.application.routes.draw do
  resources :managers
  resources :products
  resources :carts
  resources :orders
  resources :users
  resources :comments
  resources :adresses
  resources :sales
  resources :categories
  resources :stocks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ecommerce-shopping-back/app/models/adress.rb
class Adress < ApplicationRecord
end

ecommerce-shopping-back/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ecommerce-shopping-back/app/models/cart.rb
class Cart < ApplicationRecord
end

ecommerce-shopping-back/app/models/category.rb
class Category < ApplicationRecord
end

ecommerce-shopping-back/app/models/comment.rb
class Comment < ApplicationRecord
end

ecommerce-shopping-back/app/models/manager.rb
class Manager < ApplicationRecord
end

ecommerce-shopping-back/app/models/order.rb
class Order < ApplicationRecord
end

ecommerce-shopping-back/app/models/product.rb
class Product < ApplicationRecord
end

ecommerce-shopping-back/app/models/sale.rb
class Sale < ApplicationRecord
end

ecommerce-shopping-back/app/models/stock.rb
class Stock < ApplicationRecord
end

ecommerce-shopping-back/app/models/user.rb
class User < ApplicationRecord
end

ecommerce-shopping-back/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.require(:cart).permit(:produtos, :subtotal)
    end
end

ecommerce-shopping-back/app/helpers/adresses_helper.rb
module AdressesHelper
end

ecommerce-shopping-back/app/helpers/application_helper.rb
module ApplicationHelper
end

ecommerce-shopping-back/app/helpers/carts_helper.rb
module CartsHelper
end

ecommerce-shopping-back/app/helpers/categories_helper.rb
module CategoriesHelper
end

ecommerce-shopping-back/app/helpers/comments_helper.rb
module CommentsHelper
end

ecommerce-shopping-back/app/helpers/managers_helper.rb
module ManagersHelper
end

ecommerce-shopping-back/app/helpers/orders_helper.rb
module OrdersHelper
end

ecommerce-shopping-back/app/helpers/products_helper.rb
module ProductsHelper
end

ecommerce-shopping-back/app/helpers/sales_helper.rb
module SalesHelper
end

ecommerce-shopping-back/app/helpers/stocks_helper.rb
module StocksHelper
end

ecommerce-shopping-back/app/helpers/users_helper.rb
module UsersHelper
end

ecommerce-shopping-back/app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :produtos %>
    <%= form.text_field :produtos %>
  </div>

  <div class="field">
    <%= form.label :subtotal %>
    <%= form.text_field :subtotal %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

ecommerce-shopping-back/app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

ecommerce-shopping-back/app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th>Produtos</th>
      <th>Subtotal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.produtos %></td>
        <td><%= cart.subtotal %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

ecommerce-shopping-back/app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

ecommerce-shopping-back/app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Produtos:</strong>
  <%= @cart.produtos %>
</p>

<p>
  <strong>Subtotal:</strong>
  <%= @cart.subtotal %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>