ecommerce-shopping-back/config/routes.rb
Rails.application.routes.draw do
  resources :managers
  resources :products
  resources :carts
  resources :orders
  resources :users
  resources :comments
  resources :adresses
  resources :sales
  resources :categories
  resources :stocks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ecommerce-shopping-back/app/models/adress.rb
class Adress < ApplicationRecord
end

ecommerce-shopping-back/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ecommerce-shopping-back/app/models/cart.rb
class Cart < ApplicationRecord
end

ecommerce-shopping-back/app/models/category.rb
class Category < ApplicationRecord
end

ecommerce-shopping-back/app/models/comment.rb
class Comment < ApplicationRecord
end

ecommerce-shopping-back/app/models/manager.rb
class Manager < ApplicationRecord
end

ecommerce-shopping-back/app/models/order.rb
class Order < ApplicationRecord
end

ecommerce-shopping-back/app/models/product.rb
class Product < ApplicationRecord
end

ecommerce-shopping-back/app/models/sale.rb
class Sale < ApplicationRecord
end

ecommerce-shopping-back/app/models/stock.rb
class Stock < ApplicationRecord
end

ecommerce-shopping-back/app/models/user.rb
class User < ApplicationRecord
end

ecommerce-shopping-back/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:nome, :imagem, :descricao, :categoria, :preco, :likes, :peso, :dimensao)
    end
end

ecommerce-shopping-back/app/helpers/adresses_helper.rb
module AdressesHelper
end

ecommerce-shopping-back/app/helpers/application_helper.rb
module ApplicationHelper
end

ecommerce-shopping-back/app/helpers/carts_helper.rb
module CartsHelper
end

ecommerce-shopping-back/app/helpers/categories_helper.rb
module CategoriesHelper
end

ecommerce-shopping-back/app/helpers/comments_helper.rb
module CommentsHelper
end

ecommerce-shopping-back/app/helpers/managers_helper.rb
module ManagersHelper
end

ecommerce-shopping-back/app/helpers/orders_helper.rb
module OrdersHelper
end

ecommerce-shopping-back/app/helpers/products_helper.rb
module ProductsHelper
end

ecommerce-shopping-back/app/helpers/sales_helper.rb
module SalesHelper
end

ecommerce-shopping-back/app/helpers/stocks_helper.rb
module StocksHelper
end

ecommerce-shopping-back/app/helpers/users_helper.rb
module UsersHelper
end

ecommerce-shopping-back/app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :imagem %>
    <%= form.text_field :imagem %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao %>
  </div>

  <div class="field">
    <%= form.label :categoria %>
    <%= form.text_field :categoria %>
  </div>

  <div class="field">
    <%= form.label :preco %>
    <%= form.text_field :preco %>
  </div>

  <div class="field">
    <%= form.label :likes %>
    <%= form.number_field :likes %>
  </div>

  <div class="field">
    <%= form.label :peso %>
    <%= form.text_field :peso %>
  </div>

  <div class="field">
    <%= form.label :dimensao %>
    <%= form.text_field :dimensao %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

ecommerce-shopping-back/app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

ecommerce-shopping-back/app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Imagem</th>
      <th>Descricao</th>
      <th>Categoria</th>
      <th>Preco</th>
      <th>Likes</th>
      <th>Peso</th>
      <th>Dimensao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.nome %></td>
        <td><%= product.imagem %></td>
        <td><%= product.descricao %></td>
        <td><%= product.categoria %></td>
        <td><%= product.preco %></td>
        <td><%= product.likes %></td>
        <td><%= product.peso %></td>
        <td><%= product.dimensao %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

ecommerce-shopping-back/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

ecommerce-shopping-back/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @product.nome %>
</p>

<p>
  <strong>Imagem:</strong>
  <%= @product.imagem %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @product.descricao %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @product.categoria %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @product.preco %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @product.likes %>
</p>

<p>
  <strong>Peso:</strong>
  <%= @product.peso %>
</p>

<p>
  <strong>Dimensao:</strong>
  <%= @product.dimensao %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>