ecommerce-shopping-back/config/routes.rb
Rails.application.routes.draw do
  resources :managers
  resources :products
  resources :carts
  resources :orders
  resources :users
  resources :comments
  resources :adresses
  resources :sales
  resources :categories
  resources :stocks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ecommerce-shopping-back/app/models/adress.rb
class Adress < ApplicationRecord
end

ecommerce-shopping-back/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ecommerce-shopping-back/app/models/cart.rb
class Cart < ApplicationRecord
end

ecommerce-shopping-back/app/models/category.rb
class Category < ApplicationRecord
end

ecommerce-shopping-back/app/models/comment.rb
class Comment < ApplicationRecord
end

ecommerce-shopping-back/app/models/manager.rb
class Manager < ApplicationRecord
end

ecommerce-shopping-back/app/models/order.rb
class Order < ApplicationRecord
end

ecommerce-shopping-back/app/models/product.rb
class Product < ApplicationRecord
end

ecommerce-shopping-back/app/models/sale.rb
class Sale < ApplicationRecord
end

ecommerce-shopping-back/app/models/stock.rb
class Stock < ApplicationRecord
end

ecommerce-shopping-back/app/models/user.rb
class User < ApplicationRecord
end

ecommerce-shopping-back/app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :set_manager, only: [:show, :edit, :update, :destroy]

  # GET /managers
  # GET /managers.json
  def index
    @managers = Manager.all
  end

  # GET /managers/1
  # GET /managers/1.json
  def show
  end

  # GET /managers/new
  def new
    @manager = Manager.new
  end

  # GET /managers/1/edit
  def edit
  end

  # POST /managers
  # POST /managers.json
  def create
    @manager = Manager.new(manager_params)

    respond_to do |format|
      if @manager.save
        format.html { redirect_to @manager, notice: 'Manager was successfully created.' }
        format.json { render :show, status: :created, location: @manager }
      else
        format.html { render :new }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /managers/1
  # PATCH/PUT /managers/1.json
  def update
    respond_to do |format|
      if @manager.update(manager_params)
        format.html { redirect_to @manager, notice: 'Manager was successfully updated.' }
        format.json { render :show, status: :ok, location: @manager }
      else
        format.html { render :edit }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managers/1
  # DELETE /managers/1.json
  def destroy
    @manager.destroy
    respond_to do |format|
      format.html { redirect_to managers_url, notice: 'Manager was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manager
      @manager = Manager.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def manager_params
      params.fetch(:manager, {})
    end
end

ecommerce-shopping-back/app/helpers/adresses_helper.rb
module AdressesHelper
end

ecommerce-shopping-back/app/helpers/application_helper.rb
module ApplicationHelper
end

ecommerce-shopping-back/app/helpers/carts_helper.rb
module CartsHelper
end

ecommerce-shopping-back/app/helpers/categories_helper.rb
module CategoriesHelper
end

ecommerce-shopping-back/app/helpers/comments_helper.rb
module CommentsHelper
end

ecommerce-shopping-back/app/helpers/managers_helper.rb
module ManagersHelper
end

ecommerce-shopping-back/app/helpers/orders_helper.rb
module OrdersHelper
end

ecommerce-shopping-back/app/helpers/products_helper.rb
module ProductsHelper
end

ecommerce-shopping-back/app/helpers/sales_helper.rb
module SalesHelper
end

ecommerce-shopping-back/app/helpers/stocks_helper.rb
module StocksHelper
end

ecommerce-shopping-back/app/helpers/users_helper.rb
module UsersHelper
end

ecommerce-shopping-back/app/views/managers/_form.html.erb
<%= form_with(model: manager, local: true) do |form| %>
  <% if manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(manager.errors.count, "error") %> prohibited this manager from being saved:</h2>

      <ul>
      <% manager.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

ecommerce-shopping-back/app/views/managers/edit.html.erb
<h1>Editing Manager</h1>

<%= render 'form', manager: @manager %>

<%= link_to 'Show', @manager %> |
<%= link_to 'Back', managers_path %>

ecommerce-shopping-back/app/views/managers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Managers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @managers.each do |manager| %>
      <tr>
        <td><%= link_to 'Show', manager %></td>
        <td><%= link_to 'Edit', edit_manager_path(manager) %></td>
        <td><%= link_to 'Destroy', manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manager', new_manager_path %>

ecommerce-shopping-back/app/views/managers/new.html.erb
<h1>New Manager</h1>

<%= render 'form', manager: @manager %>

<%= link_to 'Back', managers_path %>

ecommerce-shopping-back/app/views/managers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_manager_path(@manager) %> |
<%= link_to 'Back', managers_path %>